name: Update 539 stats

on:
  schedule:
    # 22:05 Asia/Taipei (UTC+8) = 14:05 UTC, Mon-Sat
    - cron: '5 14 * * 1-6'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Generate JSON (TZ=Asia/Taipei)
        env:
          TZ: Asia/Taipei
        run: |
          python backend/scrape_539.py --out-dir web/public

      - name: Commit & push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A web/public
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: update 539 stats $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
          git push
