name: Update 539 stats

on:
  schedule:
    # 22:05 Asia/Taipei (= 14:05 UTC), Mon–Sat
    - cron: '5 14 * * 1-6'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Generate JSON to docs/
        run: |
          mkdir -p docs
          python backend/scrape_539.py --out-dir docs
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/539_*.json
          git commit -m "chore: update 539 stats [skip ci]" || echo "No changes"
          git push
